#!/usr/bin/env python3
"""Collect every results/raw/*.summary.json into results/SUMMARY.md (one table per scenario).
Numbers are copied from the summaries the load generator wrote; nothing is typed by hand.
usage: python3 bench/summarize.py [results_dir]"""
import json, pathlib, sys

root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "results")
runs = []
for f in sorted((root / "raw").glob("*.summary.json")):
    j = json.loads(f.read_text())
    runs.append((f.name, j["meta"], j["cells"]))

COLS = {
    "prefill": [("in_tokens_mean", "in tok"), ("ttft_p50_s", "TTFT p50 s"), ("prefill_tok_s_p50", "prefill tok/s")],
    "decode": [("concurrency", "conc"), ("in_tokens_mean", "in"), ("out_tokens_mean", "out"),
               ("ttft_p50_s", "TTFT p50 s"), ("ttft_p90_s", "TTFT p90 s"),
               ("user_decode_tok_s_p50", "per-user tok/s p50"), ("user_decode_tok_s_p10", "per-user tok/s p10"),
               ("agg_out_tok_s", "aggregate out tok/s"), ("errors", "err")],
    "agent": [("users", "users"), ("final_ctx_tokens_max", "max ctx"), ("turn_ttft_p50_s", "turn TTFT p50 s"),
              ("turn_ttft_p90_s", "turn TTFT p90 s"), ("user_decode_tok_s_p50", "per-user tok/s p50"),
              ("cached_share", "cached share"), ("session_s_p50", "session s p50"), ("session_s_max", "session s max"),
              ("agg_out_tok_s", "aggregate out tok/s"), ("errors", "err")],
}

out = ["# Results\n", "Generated by `bench/summarize.py` from `results/raw/*.summary.json`. Do not edit by hand.\n"]
for scen, cols in COLS.items():
    rows = [(n, m, c) for n, m, c in runs if m["scenario"] == scen]
    if not rows:
        continue
    out.append(f"\n## {scen}\n")
    out.append("| engine | config | " + " | ".join(h for _, h in cols) + " | source |")
    out.append("|" + "---|" * (len(cols) + 3))
    for name, meta, cells in rows:
        for c in cells:
            vals = ["" if c.get(k) is None else str(c.get(k)) for k, _ in cols]
            out.append(f"| {meta['engine']} | {meta['tag']} | " + " | ".join(vals) + f" | {name.split('.')[0]} |")
lb = sorted((root / "llamabench").glob("*_bench.jsonl"))
if lb:
    out.append("\n## llama.cpp engine-only (llama-bench, q8_0 KV, flash attention)\n")
    out.append("| file | ubatch | prompt | gen | depth | tok/s | +/- |")
    out.append("|---|---|---|---|---|---|---|")
    for f in lb:
        for line in f.read_text().splitlines():
            if line.startswith("{"):
                r = json.loads(line)
                out.append(f"| {f.name.replace('_bench.jsonl', '')} | {r['n_ubatch']} | {r['n_prompt']} | {r['n_gen']} | "
                           f"{r.get('n_depth', 0)} | {r['avg_ts']:.1f} | {r['stddev_ts']:.1f} |")
    out.append("\n### decode with N parallel sequences (llama-batched-bench, 1024-token prompts, 128 generated)\n")
    out.append("| file | sequences | prefill tok/s | total decode tok/s | per-sequence tok/s |")
    out.append("|---|---|---|---|---|")
    for f in sorted((root / "llamabench").glob("*_batched.jsonl")):
        for line in f.read_text().splitlines():
            if line.startswith("{"):
                r = json.loads(line)
                out.append(f"| {f.name.replace('_batched.jsonl', '')} | {r['pl']} | {r['speed_pp']:.1f} | "
                           f"{r['speed_tg']:.1f} | {r['speed_tg'] / r['pl']:.1f} |")
(root / "SUMMARY.md").write_text("\n".join(out) + "\n")
print(f"wrote {root / 'SUMMARY.md'} from {len(runs)} runs")
